homeassistant:
  name: Geral
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 17
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
#  customize_domain: !include customize_domain.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config
    - /config/script
config:


frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
  

    
    



############
# INCLUDES #
############

group: !include groups.yaml
sensor: !include sensor.yaml
device_tracker: !include device_tracker.yaml
tts: !include googletts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
#script: !include script.yaml
proximity: !include proximity.yaml
history_graph: !include history_graph.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml




xiaomi_aqara:
  discovery_retry: 5
  gateways:   
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key
      host: 192.168.1.2

    
logbook:
map:
discovery:
sun:
conversation:
logger:
  default: error
#  logs:
#    homeassistant.components.mqtt: debug
recorder:
  purge_keep_days: 1
  purge_interval: 1
history:
#logbook:



  
http:
  base_url: !secret meu_dns
  api_password: !secret api_password_http
  ip_ban_enabled: True
  login_attempts_threshold: 3
  

   
#google:
#  client_id: !secret client_id google
#  client_secret: !secret client_secret_google
#  
  
media_extractor:

#weather:
#  - platform: ipma
  
  


  

