homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   

  customize:
    sensor.portawc:
      icon: mdi:glassdoor
    switch.radio:
      friendly_name: "Rádio"
      icon: mdi:radio   
    switch.luz_casa_de_banho:
      icon: mdi:lightbulb-outline

  



###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################  

automation:

#Ligar rádio ou desligar quando o botao é pressionado       


  - alias: ligar radio wc
    hide_entity: true
    trigger:
      platform: mqtt
      topic: tele/teste/RESULT
    condition:
      condition: template
      value_template: '{{ trigger.payload_json.RfReceived.Data == "E0EC9D" }}'      
    action:
      service_template: >
       {% if is_state('switch.radio', 'off') %}
       switch.turn_on  
       {%- elif is_state('switch.radio', 'on') -%}
       switch.turn_off
       {% endif %}
      entity_id: switch.radio

###############################################################################
#                                                                             #
#                           S C R I P T S                                     #
#                                                                             #
###############################################################################
###############################################################################
#                                                                             #
#                           S E N S O R S                                     #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                           S W I T C H E S                                   #
#                                                                             #
###############################################################################  

switch:
  - platform: mqtt
    name: "Luz Casa de Banho"
    state_topic: "stat/sonoffwcluz/POWER"
    command_topic: "cmnd/sonoffwcluz/power"
    availability_topic: "tele/sonoffwcluz/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  
  - platform: mqtt
    name: "Rádio"
    state_topic: "stat/sonoff69/POWER"
    command_topic: "cmnd/sonoff69/power"
    availability_topic: "tele/sonoff69/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  
###############################################################################
#                                                                             #
#                           B I N A R Y _ S E N S O R S                       #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                          I N P U T   B O O L E A N S                        #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                           G R O U P                                         #
#                                                                             #
###############################################################################   


group:
  
  wc:
    view: yes
    icon: mdi:human-male-female
    control: hidden
    entities:
      - group.casadebanhogroup


  casadebanhogroup:
    control: hidden
    name: Casa de Banho
    entities:
      - switch.radio
      - switch.luz_casa_de_banho       





  
 