homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
        
  customize:
 
    switch.interruptor_quarto:
      icon: mdi:lightbulb-outline 

switch:

  - platform: mqtt
    name: "Interruptor Quarto"
    state_topic: "stat/sonoffquarto/POWER"
    command_topic: "cmnd/sonoffquarto/POWER"
    availability_topic: "tele/sonoffquarto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
         
###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################     

###############################################################################
#                                                                             #
#                           B I N A R Y   S E N S O R S                       #
#                                                                             #
##############################################################################         
        
binary_sensor:

  - platform: mqtt
    name: "Sonoff Interruptor Quarto"
    state_topic: "tele/sonoffquarto/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"

      
###############################################################################
#                                                                             #
#                           G R O U P                                         #
#                                                                             #
###############################################################################       
      
group:
  
  quarto:
    view: yes
    icon: mdi:hotel
    entities:
      - group.quartogroup

  quartogroup:
    control: hidden
    name: Quarto
    entities:
      - switch.interruptor_quarto


     
      

      
###############################################################################
#                                                                             #
#                           S E N S O R S                                     #
#                                                                             #
###############################################################################  